version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - 8080:8080
    volumes:
      - .:/go/app
    command: realize start --name="backend" --run
